# Generated by Django 3.2.25 on 2024-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome do Consumidor')),
                ('document', models.CharField(max_length=14, unique=True, verbose_name='Documento(CPF/CNPJ)')),
                ('city', models.CharField(max_length=128, verbose_name='Cidade')),
                ('state', models.CharField(max_length=128, verbose_name='Estado')),
                ('consumer_type', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=128, verbose_name='Tipo de Consumidor')),
                ('consumption_range', models.IntegerField(verbose_name='Faixa de Consumo')),
                ('cover_value', models.IntegerField(verbose_name='Valor da Cobertura')),
                ('distributor_tax', models.FloatField(default=0.0, verbose_name='Tarifa da Distribuidora')),
                ('discount_value', models.FloatField(verbose_name='Valor do Desconto')),
            ],
        ),
    ]
